### ISSUE TITLE
偶发乱码

### ISSUE THREAD

**Issue by aRe00t** [qiniu/ip17mon-java#1]
flink(多线程环境) 输出 json 到 elasticsearch, 同一个 ip 地址, 有的记录显示正常, 有的显示乱码.
对比官方 java 修改2行后, 再也没出现过乱码.
不懂原理, 求解答...
加上了 ut8编码, 和 split中的-1
```
  LocationInfo buildInfo(byte[] bytes, int offset, int len) {
    String str = new String(bytes, offset, len, Charset.forName("UTF-8"));
    String[] ss = str.split("\t", -1);
```

**Comment by aRe00t** [comment]
<img width="274" alt="qq20170224-0 2x" src="https://cloud.githubusercontent.com/assets/1515224/23301988/9e92623a-fac7-11e6-8233-5c84d5b9ffb5.png">

**Comment by longbai** [comment]
收到，多谢，我看下

**Comment by longbai** [comment]
参照您的建议修复了，应该是默认 ascii 码，有时不识别。 至于同一个IP 为啥时好时坏 不清楚，能麻烦给个出问题的IP 给我么？

**Comment by aRe00t** [comment]
<img width="949" alt="qq20170307-0 2x" src="https://cloud.githubusercontent.com/assets/1515224/23643703/534d60c0-033e-11e7-9bb1-4825f23660dc.png">
集群有6台机器, 猜测可能和某台配置有关系, 问题解决后没有进一步研究...

**Comment by longbai** [comment]
哦，那有可能是某一台服务器的默认编码是ascii, 导致这个问题。新版本0.1已经发布到maven了。
